import type { SocialColor } from '$lib/components/ui/common';

export type ButtonVariant = 'filled' | 'light' | 'outline' | 'subtle' | 'gradient';

export const buttonVariantColorsMap: Record<ButtonVariant, Record<SocialColor, string>> = {
  filled: {
    dark: 'text-white bg-gray-900',
    gray: 'text-white bg-gray-500',
    red: 'text-white bg-red-500',
    pink: 'text-white bg-pink-500',
    grape: 'text-white bg-purple-500',
    violet: 'text-white bg-violet-500',
    indigo: 'text-white bg-indigo-500',
    blue: 'text-white bg-blue-500',
    cyan: 'text-white bg-cyan-500',
    teal: 'text-white bg-teal-500',
    green: 'text-white bg-green-500',
    lime: 'text-white bg-lime-500',
    yellow: 'text-white bg-yellow-500',
    orange: 'text-white bg-orange-500',
  },
  light: {
    dark: 'text-gray-900 bg-gray-200',
    gray: 'text-gray-500 bg-gray-200',
    red: 'text-red-500 bg-red-200',
    pink: 'text-pink-500 bg-pink-200',
    grape: 'text-purple-500 bg-purple-200',
    violet: 'text-violet-500 bg-violet-200',
    indigo: 'text-indigo-500 bg-indigo-200',
    blue: 'text-blue-500 bg-blue-200',
    cyan: 'text-cyan-500 bg-cyan-200',
    teal: 'text-teal-500 bg-teal-200',
    green: 'text-green-500 bg-green-200',
    lime: 'text-lime-500 bg-lime-200',
    yellow: 'text-yellow-500 bg-yellow-200',
    orange: 'text-orange-500 bg-orange-200',
  },
  outline: {
    dark: 'text-gray-900 border-gray-900 border',
    gray: 'text-gray-500 border-gray-500 border',
    red: 'text-red-500 border-red-500 border',
    pink: 'text-pink-500 border-pink-500 border',
    grape: 'text-purple-500 border-purple-500 border',
    violet: 'text-violet-500 border-violet-500 border',
    indigo: 'text-indigo-500 border-indigo-500 border',
    blue: 'text-blue-500 border-blue-500 border',
    cyan: 'text-cyan-500 border-cyan-500 border',
    teal: 'text-teal-500 border-teal-500 border',
    green: 'text-green-500 border-green-500 border',
    lime: 'text-lime-500 border-lime-500 border',
    yellow: 'text-yellow-500 border-yellow-500 border',
    orange: 'text-orange-500 border-orange-500 border',
  },
  subtle: {
    dark: 'text-gray-900 bg-white hover:bg-gray-100',
    gray: 'text-gray-500 bg-white hover:bg-gray-100',
    red: 'text-red-500 bg-white hover:bg-red-100',
    pink: 'text-pink-500 bg-white hover:bg-pink-100',
    grape: 'text-purple-500 bg-white hover:bg-purple-100',
    violet: 'text-violet-500 bg-white hover:bg-violet-100',
    indigo: 'text-indigo-500 bg-white hover:bg-indigo-100',
    blue: 'text-blue-500 bg-white hover:bg-blue-100',
    cyan: 'text-cyan-500 bg-white hover:bg-cyan-100',
    teal: 'text-teal-500 bg-white hover:bg-teal-100',
    green: 'text-green-500 bg-white hover:bg-green-100',
    lime: 'text-lime-500 bg-white hover:bg-lime-100',
    yellow: 'text-yellow-500 bg-white hover:bg-yellow-100',
    orange: 'text-orange-500 bg-white hover:bg-orange-100',
  },
  gradient: {
    dark: 'text-white bg-gradient-to-r from-gray-900 to-gray-800',
    gray: 'text-white bg-gradient-to-r from-gray-500 to-gray-400',
    red: 'text-white bg-gradient-to-r from-red-500 to-red-400',
    pink: 'text-white bg-gradient-to-r from-pink-500 to-pink-400',
    grape: 'text-white bg-gradient-to-r from-purple-500 to-purple-400',
    violet: 'text-white bg-gradient-to-r from-violet-500 to-violet-400',
    indigo: 'text-white bg-gradient-to-r from-indigo-500 to-indigo-400',
    blue: 'text-white bg-gradient-to-r from-blue-500 to-blue-400',
    cyan: 'text-white bg-gradient-to-r from-cyan-500 to-cyan-400',
    teal: 'text-white bg-gradient-to-r from-teal-500 to-teal-400',
    green: 'text-white bg-gradient-to-r from-green-500 to-green-400',
    lime: 'text-white bg-gradient-to-r from-lime-500 to-lime-400',
    yellow: 'text-white bg-gradient-to-r from-yellow-500 to-yellow-400',
    orange: 'text-white bg-gradient-to-r from-orange-500 to-orange-400',
  }
};
