import { default as ErrorIcon } from './tabler--alert-octagon.svelte';

export { default as AccessPoint } from './tabler--access-point.svelte';
export { default as Email } from './tabler--email.svelte';
export { default as ClosedEye } from './tabler--eye-closed.svelte';
export { default as OpenEye } from './tabler--open-eye.svelte';
export { default as Home } from './tabler--home.svelte';
export { default as Flame } from './tabler--flame.svelte';
export { default as MapPin } from './tabler--map-pin.svelte';
export { default as Plus } from './tabler--plus.svelte';
export { default as Minus } from './tabler--minus.svelte';
export { default as Search } from './tabler--search.svelte';
export { default as ShoppingBag } from './tabler--shopping-bag.svelte';
export { default as ShoppingBagPlus } from './tabler--shopping-bag-plus.svelte';
export { default as Lock } from './tabler--lock.svelte';
export { default as InforCircle } from './tabler--info-circle.svelte';
export { default as Check } from './tabler--check.svelte';
export { default as Warn } from './tabler--alert-triangle.svelte';
export { default as Heart } from './tabler--heart.svelte';
export { default as HeartFilled } from './tabler--heart-filled.svelte';
export { default as ChevronLeft } from './tabler--chevron-left.svelte';
export { default as ChevronRight } from './tabler--chevron-right.svelte';
export { default as TagFilled } from './tabler--tag-filled.svelte';
export { default as Facebook } from './logo--facebook.svelte';
export { default as Google } from './logo--google.svelte';
export { default as Twitter } from './logo--twitter.svelte';
export { default as Star } from './tabler--star.svelte';
export { default as StarFilled } from './tabler--star-filled.svelte';
export { default as MingcuteHome } from './mingcute--home.svelte';
export { default as IonFlame } from './ion-flame.svelte';
export { default as FileText } from './tabler--file-text.svelte';
export { default as HeadSet } from './tabler--headset.svelte';
export { default as SettingCheck } from './tabler--setting-check.svelte';
export { default as PackageExport } from './tabler--package-export.svelte';
export { default as ArrowDownRight } from './tabler--arrow-down-right.svelte';
export { default as Photo } from './tabler--photo.svelte';
export { default as BurstSale } from './foundation-burst-sale.svelte';

export { default as Icon } from './icon.svelte';
export { ErrorIcon };

export type IconType = typeof ErrorIcon;
