name: "Web app setup"
description: "Set up NPM and dependencies"

runs:
  using: "composite"
  # steps:
  #   - name: ci/setup-node
  #     uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
  #     id: setup_node
  #     with:
  #       node-version-file: ".nvmrc"
  #       cache: npm
  #       cache-dependency-path: 'package-lock.json'
  #   - name: ci/get-node-modules
  #     shell: bash
  #     working-directory: .
  #     run: |
  #       make node_modules

  steps:
    # - uses: actions/checkout@v4
    # - uses: actions/setup-node@v4
    #   with:
    #     node-version: 18

    - name: Get PNPM version from package.json
      id: pnpm-version
      run: echo "pnpm_version=$(cat package.json | jq '.engines.pnpm' | sed -E 's/[^0-9.]//g')" >> $GITHUB_OUTPUT

    - name: Install PNPM
      uses: pnpm/action-setup@v2
      with:
        version: ${{ steps.pnpm-version.outputs.pnpm_version }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm --version && pnpm install --frozen-lockfile

    # - name: Install dependencies
    #   run: pnpm install

    # - name: Run tests
    #   run: pnpm test