<script lang="ts">
	import { T } from '$i18n';
	import SectionHeader from '$lib/components/common/section-header.svelte';
	import { Input, TextArea } from '$lib/components/ui/Input';
	import type { ProductCreateInput, SeoInput } from '$lib/gql/graphql';
	import { CommonState } from '$lib/utils/common.svelte';
	import { SitenameCommonClassName } from '$lib/utils/utils';
	import { createSchemaHandler } from '$lib/utils/zod.svelte';
	import { PRODUCT_SLUG_MAX_LENGTH } from './utils';
	import slugify from 'slugify';
	import { object, string } from 'zod';

	type Props = {
		seo?: SeoInput;
		/** reference for creating default seo */
		productName: ProductCreateInput['name'];
		slug: ProductCreateInput['slug'];
		formOk: boolean;
		loading: boolean;
	};

	const SEO_DESCRIPTION_MAX_LENGTH = 300; // saleor reference
	const SEO_TITLE_MAX_LENGTH = 70;

	let {
		productName,
		slug = $bindable(),
		seo = $bindable({}),
		formOk = $bindable(),
		loading,
	}: Props = $props();

	const seoSchema = object({
		slug: string()
			.min(1, $CommonState.FieldRequiredError)
			.nonempty($CommonState.FieldRequiredError)
			.max(PRODUCT_SLUG_MAX_LENGTH, {
				error: $T('error.lengthInvalid', {
					name: $T('product.prdSlug'),
					min: 1,
					max: PRODUCT_SLUG_MAX_LENGTH,
				}),
			}),
		title: string()
			.min(1, $CommonState.FieldRequiredError)
			.nonempty($CommonState.FieldRequiredError)
			.max(SEO_TITLE_MAX_LENGTH, {
				error: $T('error.lengthInvalid', {
					name: $T('product.seoTitle'),
					min: 1,
					max: SEO_TITLE_MAX_LENGTH,
				}),
			}),
		description: string()
			.min(1, $CommonState.FieldRequiredError)
			.nonempty($CommonState.FieldRequiredError)
			.max(SEO_DESCRIPTION_MAX_LENGTH, {
				error: $T('error.lengthInvalid', {
					name: $T('product.seoDescription'),
					min: 1,
					max: SEO_DESCRIPTION_MAX_LENGTH,
				}),
			}),
	});

	const SchemaHandler = createSchemaHandler(
		seoSchema,
		() => ({
			slug,
			title: seo.title,
			description: seo.description,
		}),
		(ok) => (formOk = ok),
	);

	/** Tracks the last auto-generated slug so we don't overwrite user edits */
	let lastAutoGeneratedSlug = $state('');

	$effect(() => {
		if (productName) {
			const newSlug = slugify(productName, { lower: true, strict: true });
			lastAutoGeneratedSlug = newSlug;
			// Only overwrite slug if user hasn't manually edited it
			if (!slug || slug === lastAutoGeneratedSlug) {
				slug = newSlug;
			}
			seo.title = productName;
		}
	});
</script>

<div class={SitenameCommonClassName}>
	<SectionHeader>{$T('common.seoInfo')}</SectionHeader>
	<Input
		placeholder={$T('product.prdSlug')}
		bind:value={slug}
		class="mb-1"
		inputDebounceOption={{ onInput: SchemaHandler.validate }}
		onblur={SchemaHandler.validate}
		variant={$SchemaHandler?.slug?.length ? 'error' : 'info'}
		subText={$SchemaHandler?.slug?.[0]}
		required
		label={$T('product.prdSlug')}
		disabled={loading}
	/>
	<Input
		bind:value={seo.title}
		placeholder={$T('product.seoTitle')}
		type="text"
		class="mb-1"
		inputDebounceOption={{ onInput: SchemaHandler.validate }}
		onblur={SchemaHandler.validate}
		variant={$SchemaHandler?.title?.length ? 'error' : 'info'}
		subText={$SchemaHandler?.title?.[0]}
		label={$T('product.seoTitle')}
		required
		disabled={loading}
	/>
	<TextArea
		bind:value={seo.description}
		placeholder={$T('product.seoDescription')}
		type="text"
		inputClass="min-h-20"
		onblur={SchemaHandler.validate}
		inputDebounceOption={{ onInput: SchemaHandler.validate }}
		variant={$SchemaHandler?.description?.length ? 'error' : 'info'}
		subText={$SchemaHandler?.description?.[0] ||
			`${seo?.description?.length || 0} / ${SEO_DESCRIPTION_MAX_LENGTH}`}
		label={$T('product.seoDescription')}
		required
		disabled={loading}
	/>
</div>
